global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  http:
    address: 0.0.0.0:80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

  https:
    address: 0.0.0.0:443

certificatesResolvers:
  # Example Resolver
  cloudflare:
    acme:
      email: # TODO: email in .env
      storage: /etc/traefik/acme/cloudflare/certs.json
      caServer: https://acme-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: cloudflare
        resolvers: # TODO: Can I use Quad9 instead?
          - "1.1.1.1:53"
          - "1.0.0.1:53"


log:
  level: DEBUG
#  filePath: log/traefik.log
#  format: json

accessLog:
  filePath: /var/log/traefik/access.json
  format: json
  addInternals: true # FIXME: yaml linter marks this a error. Can it be ignored?

api:
#  insecure: true
  dashboard: true
  disableDashboardAd: true

#ping:
#  entryPoint: traefik

providers:
  file:
    directory: /etc/traefik/services
    watch: false
